
datum_latitude: &datum_latitude 51.2280081111
datum_longitude: &datum_longitude 0.5033901111


mapviz_initialize_origin:
  local_xy_origins: 
    - {
    name: dont_change_this,
    latitude: *datum_latitude,
    longitude: *datum_longitude,
    altitude: 100.0,
    heading: 0.0
    }

navsat_transform_node:
  magnetic_declination_radians: 0.0
  yaw_offset: 0.0
  zero_altitude: true
  broadcast_utm_transform: false
  broadcast_utm_transform_as_parent_frame: false
  publish_filtered_gps: true
  use_odometry_yaw: false
  wait_for_datum: true
  datum: [ *datum_latitude, *datum_longitude, 0.0]